name: API CI/CD
on:
  push:
    branches: [ "main" ]
    paths:
      - 'BicepGithub/**'
      - '.github/workflows/api-cicd.yml'
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
        WEBAPP_NAME: demo-api   #must match output in Bicep (namePrefix-api)
        DOTNET_VERSION: '8.0.x'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore, Build, Publish
        working-directory: BicepGithub
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o out
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: BicepGithub/out
