name: Deploy Infra (Bicep)
on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**.bicep'
      - '.github/workflows/infra.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - uses: actions/checkout@v4
        - uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Deploy Bicep
          uses: azure/arm-deploy@v2
          with:
            scope: resourcegroup
            resourceGroupName: rg-sb-api-dev
            template: infra/main.bicep
            parameters: >
              location=australiaeast
              namePrefix=demo
              queueName=work-items
              sku=F1
              sbSku=Standard
            deploymentName: demo-infra-${{ github.run_number }}
